Repository affanzanuar/MovieApp, pull requests merged in 2022-09, with the labels that each got.

#5 Feature series
  .idea/discord.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/affan/movieapp/view/main/MainActivity.kt
  app/src/main/java/com/affan/movieapp/view/main/Series/SeriesAdapter.kt
  app/src/main/java/com/affan/movieapp/view/main/Series/SeriesData.kt
  app/src/main/java/com/affan/movieapp/view/main/Series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/account/AccountFragment.kt
  app/src/main/res/drawable/background_white_rounded.xml
  app/src/main/res/drawable/ic_baseline_search_24.xml
  app/src/main/res/drawable/ic_home_1.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_movies.xml
  app/src/main/res/drawable/ic_series.xml
  app/src/main/res/drawable/ic_user_1.xml
  app/src/main/res/drawable/nav_background_curved.xml
  app/src/main/res/drawable/postertest.jpg
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/card_layout.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_series.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: enhancement

#6 Revert "Feature series"
  .idea/discord.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/affan/movieapp/view/main/MainActivity.kt
  app/src/main/java/com/affan/movieapp/view/main/Series/SeriesAdapter.kt
  app/src/main/java/com/affan/movieapp/view/main/Series/SeriesData.kt
  app/src/main/java/com/affan/movieapp/view/main/Series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/account/AccountFragment.kt
  app/src/main/res/drawable/background_white_rounded.xml
  app/src/main/res/drawable/ic_baseline_search_24.xml
  app/src/main/res/drawable/ic_home_1.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_movies.xml
  app/src/main/res/drawable/ic_series.xml
  app/src/main/res/drawable/ic_user_1.xml
  app/src/main/res/drawable/nav_background_curved.xml
  app/src/main/res/drawable/postertest.jpg
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/card_layout.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_series.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: help wanted

#8 change layout height on item top movies layout : warp content to match parent
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/res/drawable/ic_logo.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_top_movies.xml
Labels: bug

#10 merge all fragment to bottom navigation
  app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#11 remove fragment home from logo bottom nav
  app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#13 Feature movies
  .idea/misc.xml
  app/src/main/java/com/affan/movieapp/data/Data.kt
  app/src/main/java/com/affan/movieapp/view/main/MainActivity.kt
  app/src/main/java/com/affan/movieapp/view/main/home/movies/MoviesData.kt
  app/src/main/java/com/affan/movieapp/view/main/home/movies/MoviesFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/movies/MoviesData.kt
  app/src/main/java/com/affan/movieapp/view/main/movies/MoviesFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/movies/MoviesPresenterImpl.kt
  app/src/main/java/com/affan/movieapp/view/main/movies/adapter/MoviesAdapter.kt
  app/src/main/java/com/affan/movieapp/view/main/movies/presenter/MoviesPresenter.kt
  app/src/main/java/com/affan/movieapp/view/main/movies/presenter/MoviesView.kt
  app/src/main/res/layout/fragment_movies.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#14 Feature series
  app/src/main/java/com/affan/movieapp/data/Data.kt
  app/src/main/java/com/affan/movieapp/view/main/series/SeriesData.kt
  app/src/main/java/com/affan/movieapp/view/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/series/SeriesPresenterImpl.kt
  app/src/main/java/com/affan/movieapp/view/main/series/adapter/SeriesAdapter.kt
  app/src/main/java/com/affan/movieapp/view/main/series/presenter/SeriesPresenter.kt
  app/src/main/java/com/affan/movieapp/view/main/series/presenter/SeriesView.kt
Labels: enhancement

#15 Feature splash screen
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/affan/movieapp/view/main/MainActivity.kt
  app/src/main/java/com/affan/movieapp/welcoming/LandingPage.kt
  app/src/main/java/com/affan/movieapp/welcoming/LoginActivity.kt
  app/src/main/res/drawable-hdpi/logo.png
  app/src/main/res/drawable-ldpi/logo.png
  app/src/main/res/drawable-mdpi/logo.png
  app/src/main/res/drawable-xhdpi/logo.png
  app/src/main/res/drawable-xxhdpi/logo.png
  app/src/main/res/drawable-xxxhdpi/logo.png
  app/src/main/res/layout/activity_landing_page.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#17 Feature detail ms
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/affan/movieapp/data/Data.kt
  app/src/main/java/com/affan/movieapp/model/MoviesOrSeries.kt
  app/src/main/java/com/affan/movieapp/view/main/details/DetailsActivity.kt
  app/src/main/java/com/affan/movieapp/view/main/home/HomeFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/home/adapter/HorizontalListAdapter.kt
  app/src/main/java/com/affan/movieapp/view/main/home/adapter/TopMoviesAdapter.kt
  app/src/main/res/drawable/arrow_left.png
  app/src/main/res/drawable/default_photo_profile.png
  app/src/main/res/drawable/heart.png
  app/src/main/res/drawable/poster_doctor_strange.jpg
  app/src/main/res/drawable/poster_iron_fist.jpg
  app/src/main/res/drawable/poster_kkn_di_desa_penari.jpg
  app/src/main/res/drawable/poster_lightyear.jpg
  app/src/main/res/drawable/poster_she_hulk.jpg
  app/src/main/res/layout/activity_details.xml
  app/src/main/res/layout/item_container_review.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#18 "Make layout favorite. Make activity, adapter, presenter Favorite. In…
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/affan/movieapp/view/main/account/AccountFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/account/myfavorite/FavoriteActivity.kt
  app/src/main/java/com/affan/movieapp/view/main/account/myfavorite/FavoritePresenterImp.kt
  app/src/main/java/com/affan/movieapp/view/main/account/myfavorite/adapter/FavoriteAdapter.kt
  app/src/main/java/com/affan/movieapp/view/main/account/myfavorite/presenter/FavoritePresenter.kt
  app/src/main/java/com/affan/movieapp/view/main/account/myfavorite/presenter/FavoriteView.kt
  app/src/main/java/com/affan/movieapp/view/main/details/adapter/ReviewAdapter.kt
  app/src/main/res/layout/activity_favorite.xml
  app/src/main/res/layout/item_container_favorite.xml
Labels: enhancement

#22 About profile chpass layout
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/affan/movieapp/view/main/ChangePasswordView.kt
  app/src/main/java/com/affan/movieapp/view/main/account/AccountFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/account/ChangePasswordActivity.kt
  app/src/main/java/com/affan/movieapp/view/main/account/ChangePasswordPresenter.kt
  app/src/main/java/com/affan/movieapp/view/main/account/about/AboutActivity.kt
  app/src/main/java/com/affan/movieapp/view/main/account/editprofile/EditProfileActivity.kt
  app/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  app/src/main/res/drawable/input_txt_background_curved.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#23 Remake feature details
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/affan/movieapp/data/Data.kt
  app/src/main/java/com/affan/movieapp/model/MoviesOrSeries.kt
  app/src/main/java/com/affan/movieapp/view/main/account/myfavorite/FavoriteActivity.kt
  app/src/main/java/com/affan/movieapp/view/main/details/DetailsActivity.kt
  app/src/main/java/com/affan/movieapp/view/main/details/adapter/ReviewAdapter.kt
  app/src/main/java/com/affan/movieapp/view/main/home/HomeFragment.kt
  app/src/main/res/drawable/backdrop_aquaman.jpg
  app/src/main/res/drawable/backdrop_avengers_endgame.jpg
  app/src/main/res/drawable/backdrop_avengers_infinity_war.jpg
  app/src/main/res/drawable/backdrop_beast.jpg
  app/src/main/res/drawable/backdrop_black_panther.jpg
  app/src/main/res/drawable/backdrop_breaking.jpg
  app/src/main/res/drawable/backdrop_bullet_train.jpg
  app/src/main/res/drawable/backdrop_captain_marvel.jpg
  app/src/main/res/drawable/backdrop_dc_league_of_super_pets.jpg
  app/src/main/res/drawable/backdrop_dragon_ball_super.jpg
  app/src/main/res/drawable/backdrop_gigi_and_nate.jpg
  app/src/main/res/drawable/backdrop_honk_for_jesus.jpg
  app/src/main/res/drawable/backdrop_inception.jpg
  app/src/main/res/drawable/backdrop_interstellar.jpg
  app/src/main/res/drawable/backdrop_jaws.jpg
  app/src/main/res/drawable/backdrop_joker.jpg
  app/src/main/res/drawable/backdrop_minions_the_rise_of_gru.jpg
  app/src/main/res/drawable/backdrop_nope.jpg
  app/src/main/res/drawable/backdrop_orphan_first_kill.jpg
  app/src/main/res/drawable/backdrop_pirates_of_the_caribbean.jpg
  app/src/main/res/drawable/backdrop_spiderman_far_from_home.jpg
  app/src/main/res/drawable/backdrop_the_dark_knight.jpg
  app/src/main/res/drawable/backdrop_the_invitation.jpg
  app/src/main/res/drawable/backdrop_the_lord_of_the_rings.jpg
  app/src/main/res/drawable/backdrop_the_shawshank_redemption.jpg
  app/src/main/res/drawable/backdrop_thor_love_and_thunder.jpg
  app/src/main/res/drawable/backdrop_three_thousand_years_of_longing.jpg
  app/src/main/res/drawable/backdrop_top_gun_maverick.jpg
  app/src/main/res/drawable/backdrop_transformers_dark_of_the_moon.jpg
  app/src/main/res/drawable/backdrop_where_the_crawdads_sing.jpg
  app/src/main/res/drawable/star_rating.png
  app/src/main/res/layout/activity_details.xml
Labels: documentation

#24 Remake feature details
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/affan/movieapp/view/main/details/DetailsActivity.kt
  app/src/main/res/layout/activity_details.xml
Labels: documentation

#26 Rest api home
  .idea/deploymentTargetDropDown.xml
  .idea/discord.xml
  app/build.gradle
  app/src/main/java/com/affan/movieapp/data/Data.kt
  app/src/main/java/com/affan/movieapp/model/movie/Dates.kt
  app/src/main/java/com/affan/movieapp/model/movie/Movie.kt
  app/src/main/java/com/affan/movieapp/model/movie/MovieResponse.kt
  app/src/main/java/com/affan/movieapp/model/trending/MoviesSeries.kt
  app/src/main/java/com/affan/movieapp/model/trending/TrendingResponse.kt
  app/src/main/java/com/affan/movieapp/network/ApiClient.kt
  app/src/main/java/com/affan/movieapp/network/ApiService.kt
  app/src/main/java/com/affan/movieapp/view/main/details/DetailsActivity.kt
  app/src/main/java/com/affan/movieapp/view/main/home/HomeFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/home/HomePresenterImp.kt
  app/src/main/java/com/affan/movieapp/view/main/home/adapter/HorizontalListAdapter.kt
  app/src/main/java/com/affan/movieapp/view/main/home/adapter/TopMoviesAdapter.kt
  app/src/main/java/com/affan/movieapp/view/main/home/presenter/HomeView.kt
  app/src/main/res/drawable/ic_default_horizontal.jpg
  app/src/main/res/layout/activity_details.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_horizontal_container.xml
  app/src/main/res/layout/item_top_movies.xml
Labels: enhancement

#27 Movies api
  app/build.gradle
  app/src/main/java/com/affan/movieapp/view/main/movies/MoviesFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/movies/MoviesPresenterImpl.kt
  app/src/main/java/com/affan/movieapp/view/main/movies/adapter/MoviesAdapter.kt
  app/src/main/java/com/affan/movieapp/view/main/movies/presenter/MoviesPresenter.kt
  app/src/main/java/com/affan/movieapp/view/main/movies/presenter/MoviesView.kt
  app/src/main/java/com/affan/movieapp/view/main/series/SeriesFragment.kt
Labels: enhancement

#29 series API
  app/src/main/java/com/affan/movieapp/view/main/home/HomeFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/series/Series.kt
  app/src/main/java/com/affan/movieapp/view/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/series/SeriesPresenterImpl.kt
  app/src/main/java/com/affan/movieapp/view/main/series/SeriesResponse.kt
  app/src/main/java/com/affan/movieapp/view/main/series/adapter/SeriesAdapter.kt
  app/src/main/java/com/affan/movieapp/view/main/series/network/SeriesApiClient.kt
  app/src/main/java/com/affan/movieapp/view/main/series/network/SeriesApiService.kt
  app/src/main/java/com/affan/movieapp/view/main/series/presenter/SeriesPresenter.kt
  app/src/main/java/com/affan/movieapp/view/main/series/presenter/SeriesView.kt
Labels: enhancement

#32 go to details in series
  app/src/main/java/com/affan/movieapp/view/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/series/adapter/SeriesAdapter.kt
Labels: enhancement

#34 migration from mvp to mvvm
  .idea/misc.xml
  app/src/main/java/com/affan/movieapp/model/series/SeriesResponseViewModel.kt
  app/src/main/java/com/affan/movieapp/network/ApiService.kt
  app/src/main/java/com/affan/movieapp/view/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/view/main/series/SeriesRepository.kt
  app/src/main/res/layout/card_layout.xml
Labels: enhancement

#36 implement mvvm for movies and some changes on layout
  .idea/misc.xml
  app/src/main/java/com/affan/movieapp/main/movies/MoviesFragment.kt
  app/src/main/java/com/affan/movieapp/main/movies/MoviesPresenterImpl.kt
  app/src/main/java/com/affan/movieapp/main/movies/MoviesRepository.kt
  app/src/main/java/com/affan/movieapp/main/movies/viewmodel/MoviesViewModel.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesPresenterImpl.kt
  app/src/main/java/com/affan/movieapp/main/series/adapter/SeriesAdapter.kt
  app/src/main/java/com/affan/movieapp/main/series/viewmodel/SeriesViewModel.kt
  app/src/main/java/com/affan/movieapp/network/ApiService.kt
  app/src/main/res/layout/fragment_movies.xml
  app/src/main/res/layout/fragment_series.xml
Labels: enhancement

#38 Api detail v2
  .idea/misc.xml
  app/src/main/java/com/affan/movieapp/main/account/ChangePasswordActivity.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsActivity.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsModelFactory.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsViewModel.kt
  app/src/main/java/com/affan/movieapp/main/home/view/HomeFragment.kt
  app/src/main/java/com/affan/movieapp/main/movies/MoviesFragment.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/model/details/movies/DetailsMovieResponse.kt
  app/src/main/java/com/affan/movieapp/model/details/movies/Genre.kt
  app/src/main/java/com/affan/movieapp/model/details/movies/ProductionCompany.kt
  app/src/main/java/com/affan/movieapp/model/details/movies/ProductionCountry.kt
  app/src/main/java/com/affan/movieapp/model/details/movies/SpokenLanguage.kt
  app/src/main/java/com/affan/movieapp/model/details/tv/CreatedBy.kt
  app/src/main/java/com/affan/movieapp/model/details/tv/DetailsTvResponse.kt
  app/src/main/java/com/affan/movieapp/model/details/tv/Genre.kt
  app/src/main/java/com/affan/movieapp/model/details/tv/LastEpisodeToAir.kt
  app/src/main/java/com/affan/movieapp/model/details/tv/Network.kt
  app/src/main/java/com/affan/movieapp/model/details/tv/NextEpisodeToAir.kt
  app/src/main/java/com/affan/movieapp/model/details/tv/ProductionCompany.kt
  app/src/main/java/com/affan/movieapp/model/details/tv/ProductionCountry.kt
  app/src/main/java/com/affan/movieapp/model/details/tv/Season.kt
  app/src/main/java/com/affan/movieapp/model/details/tv/SpokenLanguage.kt
  app/src/main/java/com/affan/movieapp/network/ApiService.kt
Labels: enhancement

#39 update layout for movies and series
  .idea/misc.xml
  app/src/main/java/com/affan/movieapp/main/movies/adapter/MoviesAdapter.kt
  app/src/main/java/com/affan/movieapp/main/series/adapter/SeriesAdapter.kt
  app/src/main/res/layout/card_layout.xml
  app/src/main/res/layout/fragment_movies.xml
Labels: enhancement

#40 Improv home
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/affan/movieapp/main/home/adapter/TrendingAdapter.kt
  app/src/main/java/com/affan/movieapp/main/home/view/HomeFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
Labels: documentation

#41 Commit fix bug language in coming soon
  app/src/main/java/com/affan/movieapp/main/details/DetailsActivity.kt
Labels: bug

#42 fixing layout series, and some changes on recycler view size
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/affan/movieapp/main/movies/MoviesFragment.kt
  app/src/main/java/com/affan/movieapp/main/movies/viewmodel/MoviesViewModel.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesFragment.kt
  app/src/main/res/layout/card_layout.xml
  app/src/main/res/layout/fragment_movies.xml
  app/src/main/res/layout/fragment_series.xml
Labels: documentation

#43 Fix Intent trending to detail
  .idea/misc.xml
  app/src/main/java/com/affan/movieapp/main/details/DetailsActivity.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsViewModel.kt
  app/src/main/java/com/affan/movieapp/main/home/adapter/TrendingAdapter.kt
  app/src/main/java/com/affan/movieapp/main/home/view/HomeFragment.kt
  app/src/main/res/drawable/arrow_left.png
  app/src/main/res/drawable/heart.png
  app/src/main/res/drawable/ic_default_backdrop.jpg
  app/src/main/res/drawable/ic_default_poster.jpg
  app/src/main/res/drawable/ic_default_top_movies.png
  app/src/main/res/drawable/id_background_detail_movies.jpg
  app/src/main/res/drawable/star_rating.png
  app/src/main/res/layout/activity_details.xml
Labels: bug

#44 implement get videos API
  app/src/main/java/com/affan/movieapp/main/details/DetailsActivity.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsViewModel.kt
  app/src/main/java/com/affan/movieapp/main/home/view/HomeFragment.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesRepository.kt
  app/src/main/java/com/affan/movieapp/main/series/viewmodel/SeriesViewModel.kt
  app/src/main/java/com/affan/movieapp/model/details/videos/VideosResponse.kt
  app/src/main/java/com/affan/movieapp/model/details/videos/VideosResult.kt
  app/src/main/java/com/affan/movieapp/network/ApiService.kt
Labels: enhancement

#45 layout touching on account activity
  .idea/misc.xml
  app/src/main/res/drawable/ic_baseline_person_24.xml
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_edit_profile.xml
  app/src/main/res/layout/activity_favorite.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/item_container_favorite.xml
Labels: enhancement

#46 Implement trailer
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/affan/movieapp/main/details/DetailsActivity.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsViewModel.kt
  app/src/main/java/com/affan/movieapp/main/home/adapter/TrendingAdapter.kt
  app/src/main/java/com/affan/movieapp/main/home/view/HomeFragment.kt
  app/src/main/java/com/affan/movieapp/main/home/viewmodel/HomeViewModel.kt
  app/src/main/res/drawable/heart.png
  app/src/main/res/layout/activity_details.xml
  app/src/main/res/layout/card_layout.xml
  app/src/main/res/layout/fragment_movies.xml
  app/src/main/res/layout/fragment_series.xml
Labels: enhancement

#47 Add repo home
  app/build.gradle
  app/src/main/java/com/affan/movieapp/data/Data.kt
  app/src/main/java/com/affan/movieapp/data/DataSource.kt
  app/src/main/java/com/affan/movieapp/data/local/LocalDataSource.kt
  app/src/main/java/com/affan/movieapp/data/local/room/MovieDaoImp.kt
  app/src/main/java/com/affan/movieapp/data/local/room/MovieDatabase.kt
  app/src/main/java/com/affan/movieapp/data/local/room/MoviesDao.kt
  app/src/main/java/com/affan/movieapp/data/remote/RemoteDataSource.kt
  app/src/main/java/com/affan/movieapp/di/ViewModelFactory.kt
  app/src/main/java/com/affan/movieapp/domain/Repository.kt
  app/src/main/java/com/affan/movieapp/domain/RepositoryImp.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/FavoriteActivity.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/adapter/FavoriteAdapter.kt
  app/src/main/java/com/affan/movieapp/main/home/view/HomeFragment.kt
  app/src/main/java/com/affan/movieapp/main/home/viewmodel/HomeViewModel.kt
  app/src/main/java/com/affan/movieapp/model/MoviesOrSeries.kt
Labels: documentation

#48 impl DetailsActivity.kt to Dependency Injection
  .idea/misc.xml
  app/src/main/java/com/affan/movieapp/di/ViewModelFactory.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsActivity.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsModelFactory.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsViewModel.kt
Labels: enhancement

#49 pagination series update
  app/src/main/java/com/affan/movieapp/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesRepository.kt
  app/src/main/java/com/affan/movieapp/main/series/adapter/PaginationRecyclerView.kt
  app/src/main/java/com/affan/movieapp/main/series/viewmodel/SeriesViewModel.kt
  app/src/main/java/com/affan/movieapp/model/series/SeriesResponse.kt
  app/src/main/java/com/affan/movieapp/network/ApiService.kt
Labels: enhancement

#50 dependecies injection for series
  app/src/main/java/com/affan/movieapp/data/DataSource.kt
  app/src/main/java/com/affan/movieapp/data/remote/RemoteDataSource.kt
  app/src/main/java/com/affan/movieapp/di/ViewModelFactory.kt
  app/src/main/java/com/affan/movieapp/domain/Repository.kt
  app/src/main/java/com/affan/movieapp/domain/RepositoryImp.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/main/series/adapter/PaginationRecyclerView.kt
  app/src/main/java/com/affan/movieapp/main/series/viewmodel/SeriesViewModel.kt
Labels: enhancement

#51 pagination and dependencies injection for movies
  app/src/main/java/com/affan/movieapp/data/DataSource.kt
  app/src/main/java/com/affan/movieapp/data/remote/RemoteDataSource.kt
  app/src/main/java/com/affan/movieapp/di/ViewModelFactory.kt
  app/src/main/java/com/affan/movieapp/domain/Repository.kt
  app/src/main/java/com/affan/movieapp/domain/RepositoryImp.kt
  app/src/main/java/com/affan/movieapp/main/movies/MoviesFragment.kt
  app/src/main/java/com/affan/movieapp/main/movies/MoviesRepository.kt
  app/src/main/java/com/affan/movieapp/main/movies/viewmodel/MoviesViewModel.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesRepository.kt
  app/src/main/java/com/affan/movieapp/network/ApiService.kt
Labels: enhancement

#52 fix pagination bug stuck on 2 page
  app/src/main/java/com/affan/movieapp/main/movies/MoviesFragment.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/main/series/adapter/PaginationRecyclerView.kt
Labels: bug, documentation

#53 bug fix on pagination movies and series, fully worked
  app/src/main/java/com/affan/movieapp/main/movies/MoviesFragment.kt
  app/src/main/java/com/affan/movieapp/main/movies/adapter/MoviesAdapter.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/main/series/adapter/SeriesAdapter.kt
Labels: bug, enhancement

#54 Add Feature Favorite with Room Database
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/affan/movieapp/data/Data.kt
  app/src/main/java/com/affan/movieapp/data/DataSource.kt
  app/src/main/java/com/affan/movieapp/data/local/LocalDataSource.kt
  app/src/main/java/com/affan/movieapp/data/local/room/FavoriteMovies.kt
  app/src/main/java/com/affan/movieapp/data/local/room/MovieDaoImp.kt
  app/src/main/java/com/affan/movieapp/data/local/room/MovieDatabase.kt
  app/src/main/java/com/affan/movieapp/data/local/room/MoviesDao.kt
  app/src/main/java/com/affan/movieapp/data/remote/RemoteDataSource.kt
  app/src/main/java/com/affan/movieapp/di/ViewModelFactory.kt
  app/src/main/java/com/affan/movieapp/domain/Repository.kt
  app/src/main/java/com/affan/movieapp/domain/RepositoryImp.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/FavoriteActivity.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/FavoritePresenterImp.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/adapter/FavoriteAdapter.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/presenter/FavoritePresenter.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/presenter/FavoriteView.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/viewmodel/FavoriteViewModel.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsActivity.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsViewModel.kt
  app/src/main/java/com/affan/movieapp/main/home/view/HomeFragment.kt
  app/src/main/java/com/affan/movieapp/main/movies/MoviesFragment.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesFragment.kt
  app/src/main/java/com/affan/movieapp/model/MoviesOrSeries.kt
  app/src/main/res/drawable/backdrop_dc_league_of_super_pets.jpg
  app/src/main/res/drawable/doctor_strange.jpg
  app/src/main/res/drawable/id_delete.png
  app/src/main/res/drawable/iron_fist.jpg
  app/src/main/res/drawable/kkn_di_desa_penari.jpg
  app/src/main/res/drawable/lightyear.jpg
  app/src/main/res/drawable/poster_doctor_strange.jpg
  app/src/main/res/drawable/poster_iron_fist.jpg
  app/src/main/res/drawable/poster_kkn_di_desa_penari.jpg
  app/src/main/res/drawable/poster_lightyear.jpg
  app/src/main/res/drawable/poster_she_hulk.jpg
  app/src/main/res/drawable/postertest.jpg
  app/src/main/res/drawable/she_hulk.jpg
  app/src/main/res/layout/activity_favorite.xml
  app/src/main/res/layout/card_layout.xml
  app/src/main/res/layout/item_container_favorite.xml
  app/src/main/res/layout/item_top_movies.xml
  gradle.properties
Labels: enhancement

#57 improvment_favorite
  .idea/misc.xml
  app/src/main/java/com/affan/movieapp/data/DataSource.kt
  app/src/main/java/com/affan/movieapp/data/local/LocalDataSource.kt
  app/src/main/java/com/affan/movieapp/data/local/room/MovieDatabase.kt
  app/src/main/java/com/affan/movieapp/data/local/room/MoviesDao.kt
  app/src/main/java/com/affan/movieapp/data/remote/RemoteDataSource.kt
  app/src/main/java/com/affan/movieapp/data/remote/network/ApiClient.kt
  app/src/main/java/com/affan/movieapp/data/remote/network/ApiService.kt
  app/src/main/java/com/affan/movieapp/di/ViewModelFactory.kt
  app/src/main/java/com/affan/movieapp/domain/Repository.kt
  app/src/main/java/com/affan/movieapp/domain/RepositoryImp.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/DeleteDialogFragment.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/FavoriteActivity.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/adapter/FavoriteAdapter.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/presenter/FavoriteView.kt
  app/src/main/java/com/affan/movieapp/main/account/myfavorite/viewmodel/FavoriteViewModel.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsActivity.kt
  app/src/main/java/com/affan/movieapp/main/details/DetailsViewModel.kt
  app/src/main/java/com/affan/movieapp/main/home/presenter/HomePresenterImp.kt
  app/src/main/java/com/affan/movieapp/main/movies/MoviesPresenterImpl.kt
  app/src/main/java/com/affan/movieapp/main/series/SeriesPresenterImpl.kt
  app/src/main/java/com/affan/movieapp/model/FavoriteMovies.kt
  app/src/main/res/drawable-mdpi/bg_button_dialog.xml
  app/src/main/res/layout/fragment_delete_dialog.xml
Labels: enhancement
